trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

variables:
  PythonVersion: "3.7"
  TestFolder: "$(Build.SourcesDirectory)/tests/"

jobs:
  - job: "Msrest_For_Python_CI"
    displayName: "Run Msrest For Python CI Checks"

    strategy:
      matrix:
        Windows_Python36:
          OSName: "Windows"
          OSVmImage: "MMS2019"
          PythonVersion: "3.6"
        Linux_Python38:
          OSName: "Linux"
          OSVmImage: "MMSUbuntu20.04"
          PythonVersion: "3.8"

    pool:
      name: azsdk-pool-mms-ubuntu-2004-general
      vmImage: $(OSVmImage)

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python $(PythonVersion)'
        inputs:
          versionSpec: $(PythonVersion)
      - script: |
          cd $(Build.SourcesDirectory)
          pip install pip==20.2
          pip install -r dev_requirements.txt
        displayName: "Install Env Specific Reqs in Target PyVersion $(PythonVersion)"
      - script: |
          pytest $(TestFolder)
        displayName: 'Test'
    